color_palette:
  dark_bg_fore: "#D9D9D9"
  dark_bg_back: "#054062"
api:
  mapbox: pk.eyJ1IjoiZGN5Y2xlIiwiYSI6ImNrb2J3NGZzOTAxYnAycHFkbzkxbzlzZWYifQ.DdCrbOuTjU1z4Z-wi2NpNA
  mapbox_desc: Dcycle Account Token, you should use your own here instead as this
    will change
items:
  - title: My Cool Website
    lang: en
    langs:
      - lang: fr
        path: https://www.terredesjeunes.org
    home: https://www.terredesjeunes.org
    menu:
      - id: home
        label: Home
        href: https://www.terredesjeunes.org
  - title: Accueil
    home: https://www.terredesjeunes.org
    lang: fr
    langs:
      - lang: en
        path: https://www.terredesjeunes.org
    menu:
      - id: home
        label: Accueil
        href: https://www.terredesjeunes.org
